name: Generate Wallet JSON

on:
  workflow_dispatch:
    inputs:
      hoverboards:
        description: "Number of hoverboards"
        required: true
        default: 0
      gamekeys:
        description: "Number of gamekeys"
        required: true
        default: 0
      gamecoins:
        description: "Number of gamecoins"
        required: true
        default: 0
      scoreboosters:
        description: "Number of scoreboosters"
        required: true
        default: 0
      headstarts:
        description: "Number of headstarts"
        required: true
        default: 0

jobs:
  generate-wallet:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JSON content
      id: generate
      run: |
        # Define the variables based on input
        HOVERBOARDS=${{ github.event.inputs.hoverboards }}
        GAMEKEYS=${{ github.event.inputs.gamekeys }}
        GAMECOINS=${{ github.event.inputs.gamecoins }}
        SCOREBOOSTERS=${{ github.event.inputs.scoreboosters }}
        HEADSTARTS=${{ github.event.inputs.headstarts }}

        # Create the wallet.json file with the input data
        cat <<EOF > wallet.json
        {
          "patchVersion": 0,
          "currencies": {
            "3": {"value": $HOVERBOARDS, "expirationType": 0},
            "2": {"value": $GAMEKEYS, "expirationType": 0},
            "1": {"value": $GAMECOINS, "expirationType": 0},
            "20": {"value": 0, "expirationType": 0},
            "5": {"value": $SCOREBOOSTERS, "expirationType": 0},
            "4": {"value": $HEADSTARTS, "expirationType": 0},
            "23": {"value": 0, "expirationType": 0},
            "24": {"value": 0, "expirationType": 0},
            "22": {"value": 0, "expirationType": 0},
            "21": {"value": 0, "expirationType": 0},
            "6": {"value": 0, "expirationValue": 0, "expirationType": 1}
          },
          "lootboxQueue": {"unopenedLootboxes": []},
          "currencyAllowedInRun": {"5": true, "4": true},
          "lootBoxesOpened": {
            "token_box": 0,
            "mystery_box": 0,
            "mini_mystery_box": 0,
            "super_mystery_box": 0
          },
          "ownedOnlyBuyOnceProducts": ["free_token_box"]
        }
        EOF

    - name: Show wallet.json
      run: cat wallet.json

    - name: Upload wallet.json as artifact
      uses: actions/upload-artifact@v3
      with:
        name: wallet-json
        path: wallet.json
        
