name: Generate Wallet JSON

on:
  workflow_dispatch:
    inputs:
      hoverboards:
        description: "Number of hoverboards"
        required: true
        default: 0
      gamekeys:
        description: "Number of gamekeys"
        required: true
        default: 0
      gamecoins:
        description: "Number of gamecoins"
        required: true
        default: 0
      scoreboosters:
        description: "Number of scoreboosters"
        required: true
        default: 0
      headstarts:
        description: "Number of headstarts"
        required: true
        default: 0
      eventcoins:
        description: "Number of eventcoins"
        required: true
        default: 0

jobs:
  generate-wallet:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JSON content
      id: generate
      run: |
        # Define the variables based on input
        HOVERBOARDS=${{ github.event.inputs.hoverboards }}
        GAMEKEYS=${{ github.event.inputs.gamekeys }}
        GAMECOINS=${{ github.event.inputs.gamecoins }}
        SCOREBOOSTERS=${{ github.event.inputs.scoreboosters }}
        HEADSTARTS=${{ github.event.inputs.headstarts }}
        EVENTCOINS=${{ github.event.inputs.eventcoins }}

        # Create the wallet.json file in one line
        echo "{\"version\":2,\"data\":\"{\\\"lastSaved\\\":\\\"\\\",\\\"patchVersion\\\":0,\\\"currencies\\\":{\\\"1\\\":{\\\"value\\\":$GAMECOINS},\\\"2\\\":{\\\"value\\\":$GAMEKEYS},\\\"3\\\":{\\\"value\\\":$HOVERBOARDS},\\\"4\\\":{\\\"value\\\":$HEADSTARTS},\\\"5\\\":{\\\"value\\\":$SCOREBOOSTERS},\\\"6\\\":{\\\"value\\\":$EVENTCOINS,\\\"expirationValue\\\":99999999999999,\\\"expirationType\\\":1}},\\\"lootboxQueue\\\":{\\\"unopenedLootboxes\\\":{\\\"0\\\":[],\\\"2\\\":[]}},\\\"currencyAllowedInRun\\\":{\\\"5\\\":true,\\\"4\\\":true},\\\"lootBoxesOpened\\\":{\\\"mini_mystery_box\\\":3,\\\"mystery_box\\\":7,\\\"token_box\\\":16,\\\"super_mystery_box\\\":5},\\\"ownedOnlyBuyOnceProducts\\\":[\\\"free_token_box\\\",\\\"multiplier_pack\\\",\\\"speed_crew\\\"]}\"}" > wallet.json

    - name: Show wallet.json
      run: cat wallet.json

    - name: Upload wallet.json as artifact
      uses: actions/upload-artifact@v3
      with:
        name: wallet
        path: wallet.json
        
